
import java.io.FileWriter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.jpl7.Query;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Makaveli
 */
public class CoronaPrediction extends javax.swing.JFrame {
        String g="";
        String m="";
        String duree="";
        String dist="";
        String touch="";
        String rem="";
        String res1="";
        String res2="";
        String res3="";
        String res4="";
        String res5="";
        String res6="";
        String res7="";
        String res8="";
        String res9="";
    public CoronaPrediction() {
        initComponents();
        inf.setEnabled(false);
        sup.setEnabled(false);
        resLabel.setVisible(false);
        resIcon.setVisible(false);
        conseil.setVisible(false);
        jScrollPane1.setVisible(false);
        touche.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        gel = new javax.swing.JCheckBox();
        masque = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        inf = new javax.swing.JRadioButton();
        sup = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        oui = new javax.swing.JRadioButton();
        non = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        touche = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fait1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        resIcon = new javax.swing.JLabel();
        resLabel = new javax.swing.JLabel();
        conseil = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fait = new javax.swing.JTextArea();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CoronaPrédicteur");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(51, 0, 102));
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("PREDICTEUR CORONAVIRUS");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(820, 10, 270, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banner-coronavirus.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1110, 50);

        jPanel2.setBackground(new java.awt.Color(38, 0, 77));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Avez-vous mis ou portez?:");

        gel.setBackground(new java.awt.Color(38, 0, 77));
        gel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        gel.setForeground(new java.awt.Color(255, 255, 255));
        gel.setText("Du gel désinfectant");
        gel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gelMouseClicked(evt);
            }
        });

        masque.setBackground(new java.awt.Color(38, 0, 77));
        masque.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        masque.setForeground(new java.awt.Color(255, 255, 255));
        masque.setText("Du masque");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Durée de votre sortie:");

        inf.setBackground(new java.awt.Color(38, 0, 77));
        inf.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        inf.setForeground(new java.awt.Color(255, 255, 255));
        inf.setText("Inférieure à 3 heures");
        inf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infMouseClicked(evt);
            }
        });
        inf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infActionPerformed(evt);
            }
        });

        sup.setBackground(new java.awt.Color(38, 0, 77));
        sup.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        sup.setForeground(new java.awt.Color(255, 255, 255));
        sup.setText("Supérieure à 3 heures");
        sup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supMouseClicked(evt);
            }
        });
        sup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Avez-vous respecté la distance que vous devez mettre entre vous et une personne?(1mètre): ");

        oui.setBackground(new java.awt.Color(38, 0, 77));
        oui.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        oui.setForeground(new java.awt.Color(255, 255, 255));
        oui.setText("Oui");
        oui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ouiMouseClicked(evt);
            }
        });
        oui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ouiActionPerformed(evt);
            }
        });

        non.setBackground(new java.awt.Color(38, 0, 77));
        non.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        non.setForeground(new java.awt.Color(255, 255, 255));
        non.setText("Non");
        non.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nonMouseClicked(evt);
            }
        });
        non.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quelque chose que vous avez touché:");

        touche.setBackground(new java.awt.Color(51, 0, 102));
        touche.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        touche.setForeground(new java.awt.Color(255, 255, 255));
        touche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rien", "Une personne", "Un objet à risque d'inféction", "Une personne et un objet à risque d'inféction" }));
        touche.setSelectedItem("");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 0, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_checked_20px.png"))); // NOI18N
        jButton1.setText("Valider");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(246, 4, 45));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_cancel_20px.png"))); // NOI18N
        jButton2.setText("Annuler");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(touche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oui)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(non))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(inf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sup))
                            .addComponent(gel)
                            .addComponent(masque))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gel))
                        .addGap(14, 14, 14)
                        .addComponent(masque)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inf)
                            .addComponent(sup))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oui)
                            .addComponent(non))
                        .addGap(34, 34, 34)
                        .addComponent(touche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 90, 720, 300);

        jPanel3.setBackground(new java.awt.Color(38, 0, 77));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 146, 21));
        jLabel9.setText("Faits");

        fait1.setBackground(new java.awt.Color(38, 0, 77));
        fait1.setColumns(20);
        fait1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        fait1.setForeground(new java.awt.Color(255, 255, 255));
        fait1.setRows(5);
        jScrollPane2.setViewportView(fait1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(515, 515, 515)
                .addComponent(jLabel9)
                .addContainerGap(531, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 390, 1080, 190);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 146, 21));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_next_20px.png"))); // NOI18N
        jButton4.setText("Analyser");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(10, 60, 90, 30);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 0, 102));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_flow_chart_20px.png"))); // NOI18N
        jButton5.setText("Voir l'arbre de recherche");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(890, 60, 200, 30);

        jPanel5.setBackground(new java.awt.Color(38, 0, 77));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        resIcon.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        resIcon.setForeground(new java.awt.Color(255, 255, 255));
        resIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cry.png"))); // NOI18N

        resLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        resLabel.setForeground(new java.awt.Color(0, 146, 21));
        resLabel.setText("Il y a peu de chance pour que vous soyez infecté");

        conseil.setBackground(new java.awt.Color(38, 0, 77));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("N'oubliez pas :");

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("- de laver  avec du savon vos mains");

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("et les vêtements que vous avez");

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("- et de prendre une douche");

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("porté;");

        javax.swing.GroupLayout conseilLayout = new javax.swing.GroupLayout(conseil);
        conseil.setLayout(conseilLayout);
        conseilLayout.setHorizontalGroup(
            conseilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conseilLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(conseilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11)
                    .addGroup(conseilLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(conseilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))))
                .addGap(21, 21, 21))
            .addGroup(conseilLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        conseilLayout.setVerticalGroup(
            conseilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conseilLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(resIcon)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(resLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(conseil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conseil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(723, 90, 370, 300);

        fait.setColumns(20);
        fait.setRows(5);
        jScrollPane1.setViewportView(fait);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(330, 60, 18, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1104, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void infActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infActionPerformed

    private void supActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supActionPerformed

    private void ouiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ouiActionPerformed

    private void nonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nonActionPerformed

    private void infMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infMouseClicked
        sup.setSelected(false);
        rem="remettre(non).\n";
    }//GEN-LAST:event_infMouseClicked

    private void supMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supMouseClicked
        inf.setSelected(false);
        rem="remettre(non).\n";
        if(gel.isSelected() && sup.isSelected()){
            int a=JOptionPane.showConfirmDialog(rootPane,"Avez-vous mis du gel tout les 3 heures");
            if(a==0){
                rem="remettre(oui).\n";
            }
            else if(a==1){
                rem="remettre(non).\n";
            }
            else if(a==2){
                rem="remettre(non).\n";
                sup.setSelected(false);
            }
        }
    }//GEN-LAST:event_supMouseClicked

    private void ouiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ouiMouseClicked
        non.setSelected(false);
        touche.setSelectedIndex(0);
        touche.setEnabled(false);
    }//GEN-LAST:event_ouiMouseClicked

    private void nonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nonMouseClicked
        oui.setSelected(false);
        if(non.isSelected()){
            touche.setEnabled(true);
        }
    }//GEN-LAST:event_nonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        fait.setText("");
        fait1.setText("");
        resLabel.setVisible(false);
        resIcon.setVisible(false);
        conseil.setVisible(false);
        res1="";
        res2="";
        res3="";
        res4="";
        res5="";
        res6="";
        res7="";
        res8="";
        res9="";
        g="";
        m="";
        duree="";
        dist="";
        touch="";
        if(gel.isSelected() && (!inf.isSelected() && !sup.isSelected())){
            JOptionPane.showMessageDialog(rootPane,"Précisez la durée de votre sortie s'il vous plait");
            return;
        }
        if(!oui.isSelected() && !non.isSelected()){
            JOptionPane.showMessageDialog(rootPane,"Veuillez répondre si vous avez respecté la distance que vous devez mettre entre vous et une personne ou non");
            return;
        }
        if(gel.isSelected()){
            g="misGel(oui).\n";
            if("".equals(fait1.getText())){
                fait1.setText("#Vous avez mis du gel");
            }
            else{
                fait1.setText(fait1.getText()+"\n#Vous avez mis du gel");
            }
            
        }
        else{
            g="misGel(non).\n";
            if("".equals(fait1.getText())){
                fait1.setText("#Vous n'avez pas mis du gel");
            }
            else{
                fait1.setText(fait1.getText()+"\n#Vous n'avez pas mis du gel");
            }
        }
        if(masque.isSelected()){
            m="porteM(oui).\n";
            fait1.setText(fait1.getText()+"\n#Vous avez porté du masque");
        }
        else{
            m="porteM(non).\n";
            fait1.setText(fait1.getText()+"\n#Vous n'avez pas porté du masque");
        }
        if(inf.isSelected()){
            duree="duree(inferieur).\n";
            fait1.setText(fait1.getText()+"\n#Vous êtes sorti moins de 3 heures");
        }
        if(sup.isSelected()){
            duree="duree(superieur).\n";
            fait1.setText(fait1.getText()+"\n#Vous êtes sorti plus de 3 heures");
            if("remettre(oui).\n".equals(rem)){
                fait1.setText(fait1.getText()+"\n#Vous avez remis du gel tous les 3 heures");
            }
            else{
                fait1.setText(fait1.getText()+"\n#Vous n'avez pas remis du gel tous les 3 heures");
            }
        }
        if(oui.isSelected()){
            dist="dist(oui).\n";
            if("".equals(fait1.getText())){
                fait1.setText("#Vous avez respecté la distance minimale que vous devriez mettre entre vous et une autre personne");
            }
            else{
                fait1.setText(fait1.getText()+"\n#Vous avez respecté la distance minimale que vous devriez mettre entre vous et une autre personne");
            }
        }
        if(non.isSelected()){
            dist="dist(non).\n";
            if("".equals(fait1.getText())){
                fait1.setText("#Vous n'avez pas respecté la distance minimale que vous devriez mettre entre vous et une autre personne");
            }
            else{
                fait1.setText(fait1.getText()+"\n#Vous n'avez pas respecté la distance minimale que vous devriez mettre entre vous et une autre personne");
            }
        }
        if(!"Rien".equals(touche.getSelectedItem().toString())){
            touch="toucher(oui).\n";
            if("".equals(fait1.getText())){
                fait1.setText("#Vous avez touchez à "+touche.getSelectedItem().toString());
            }
            else{
                fait1.setText(fait1.getText()+"\n#Vous avez touchez à "+touche.getSelectedItem().toString());
            }
        }
        else{
            touch="toucher(non).";
            if("".equals(fait1.getText())){
                fait1.setText("#Vous avez touchez à "+touche.getSelectedItem().toString());
            }
            else{
                fait1.setText(fait1.getText()+"\n#Vous avez touchez à "+touche.getSelectedItem().toString());
            }
        }
        if((gel.isSelected() && masque.isSelected()) || (gel.isSelected() && !masque.isSelected())){
            res1="res1():-misGel(oui),porteM(oui),((duree(inferieur),(dist(oui);(dist(non),toucher(non))));(duree(superieur),remettre(oui),(dist(oui);(dist(non),toucher(non))))).";
            res2="res2():-misGel(oui),porteM(oui),((duree(inferieur),dist(non),toucher(oui));(duree(superieur),((remettre(oui),dist(non),toucher(oui));(remettre(non),(dist(oui);(dist(non),toucher(non))))))).";
            res3="res3():-misGel(oui),porteM(oui),duree(superieur),remettre(non),dist(non),toucher(oui).";
            res4="res4():-misGel(oui),porteM(non),((duree(inferieur),(dist(oui);(dist(non),toucher(non))));(duree(superieur),remettre(oui),(dist(oui);(dist(non),toucher(non))))).";
            res5="res5():-(misGel(oui),porteM(non),((duree(inferieur),dist(non),toucher(oui));(duree(superieur),((remettre(oui),dist(non),toucher(oui));(remettre(non),(dist(oui);(dist(non),toucher(non))))))));(misGel(oui),porteM(non),duree(superieur),remettre(non),dist(non),toucher(oui)).";
        }
        else if((!gel.isSelected() && masque.isSelected()) || (!gel.isSelected() && !masque.isSelected())){
            res6="res6():-misGel(non),porteM(oui),(dist(oui);(dist(non),toucher(non))).";
            res7="res7():-misGel(non),porteM(oui),dist(non),toucher(oui).";
            res8="res8():-misGel(non),porteM(non),(dist(oui);(dist(non),toucher(non))).";
            res9="res9():-misGel(non),porteM(non),dist(non),toucher(oui).";
        }
        fait.setText(g+m+duree+rem+dist+touch+"\n"+res1+"\n"+res2+"\n"+res3+"\n"+res4+"\n"+res5+"\n"+res6+"\n"+res7+"\n"+res8+"\n"+res9);
        try{
            FileWriter fr=new FileWriter("D:/corona.pl");
            fr.write(fait.getText());
            fr.close();
        }
        catch(Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        gel.setSelected(false);
        masque.setSelected(false);
        inf.setEnabled(false);
        sup.setEnabled(false);
        inf.setSelected(false);
        sup.setSelected(false);
        oui.setSelected(false);
        non.setSelected(false);
        touche.setSelectedIndex(0);
        fait.setText("");
        fait1.setText("");
        resLabel.setVisible(false);
        resIcon.setVisible(false);
        conseil.setVisible(false);
        touche.setEnabled(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(!"".equals(fait.getText())){
            String t1="consult('D:/corona.pl')";
            Query q=new Query(t1);
            q.hasSolution();
            if((gel.isSelected() && masque.isSelected()) || (gel.isSelected() && !masque.isSelected())){
                q=new Query("res1()");
                if(q.hasSolution()){
                    ImageIcon a=new ImageIcon("D:/imagesCorona/happy1.png");
                    resIcon.setIcon(a);
                    resLabel.setText("Il n'y a pas de chance pour que vous soyez infecté");
                    resIcon.setVisible(true);
                    resLabel.setVisible(true);
                    conseil.setVisible(true);
                    JOptionPane.showMessageDialog(null, "Il n'y a pas de chance pour que vous soyez infecté");
                }
                q=new Query("res2()");
                if(q.hasSolution()){
                    ImageIcon a=new ImageIcon("D:/imagesCorona/happy.png");
                    resIcon.setIcon(a);
                    resLabel.setText("Vous avez peu de chance à être infecté");
                    resIcon.setVisible(true);
                    resLabel.setVisible(true);
                    conseil.setVisible(true);
                    JOptionPane.showMessageDialog(null, "Vous avez peu de chance à être infecté");
                }
                q=new Query("res3()");
                if(q.hasSolution()){
                    ImageIcon a=new ImageIcon("D:/imagesCorona/happy.png");
                    resIcon.setIcon(a);
                    resLabel.setText("Vous avez peu de chance à être infecté");
                    resIcon.setVisible(true);
                    resLabel.setVisible(true);
                    conseil.setVisible(true);
                    JOptionPane.showMessageDialog(null, "Vous avez peu de chance à être infecté");
                }
                q=new Query("res4()");
                if(q.hasSolution()){
                    ImageIcon a=new ImageIcon("D:/imagesCorona/happy.png");
                    resIcon.setIcon(a);
                    resLabel.setText("Vous avez peu de chance à être infecté");
                    resIcon.setVisible(true);
                    resLabel.setVisible(true);
                    conseil.setVisible(true);
                    JOptionPane.showMessageDialog(null, "Vous avez peu de chance à être infecté");
                }
                q=new Query("res5()");
                if(q.hasSolution()){
                    ImageIcon a=new ImageIcon("D:/imagesCorona/sad.png");
                    resIcon.setIcon(a);
                    resLabel.setText("Vous avez de grande chance à être infecté");
                    resIcon.setVisible(true);
                    resLabel.setVisible(true);
                    conseil.setVisible(true);
                    JOptionPane.showMessageDialog(null, "Vous avez de grande chance à être infecté si vous étiez très \nproche d'un individu infecté qui ne portait pas de masque\nSi c'est le cas, consultez un médecin au plus vite et fait un test");
                }
            }
            else if((!gel.isSelected() && masque.isSelected()) || (!gel.isSelected() && !masque.isSelected())){
                q=new Query("res6()");
                if(q.hasSolution()){
                    ImageIcon a=new ImageIcon("D:/imagesCorona/happy.png");
                    resIcon.setIcon(a);
                    resLabel.setText("Vous avez peu de chance à être infecté");
                    resIcon.setVisible(true);
                    resLabel.setVisible(true);
                    conseil.setVisible(true);
                    JOptionPane.showMessageDialog(null, "Vous avez peu de chance à être infecté");
                }
                q=new Query("res7()");
                if(q.hasSolution()){
                    ImageIcon a=new ImageIcon("D:/imagesCorona/sad.png");
                    resIcon.setIcon(a);
                    resLabel.setText("Vous avez de grande chance à être infecté");
                    resIcon.setVisible(true);
                    resLabel.setVisible(true);
                    conseil.setVisible(true);
                    JOptionPane.showMessageDialog(null, "Vous avez de grande chance à être infecté si vous avez touchez \nun individu ou un objet infecté\nSi c'est le cas, consultez un médecin au plus vite et fait un test");
                }
                q=new Query("res8()");
                if(q.hasSolution()){
                    ImageIcon a=new ImageIcon("D:/imagesCorona/sad.png");
                    resIcon.setIcon(a);
                    resLabel.setText("Vous avez de grande chance à être infecté");
                    resIcon.setVisible(true);
                    resLabel.setVisible(true);
                    conseil.setVisible(true);
                    JOptionPane.showMessageDialog(null, "Vous avez de grande chance à être infecté si vous étiez très \nproche d'un individu infecté qui ne portait pas de masque\nSi c'est le cas, consultez un médecin au plus vite et fait un test");

                }
                q=new Query("res9()");
                if(q.hasSolution()){
                    ImageIcon a=new ImageIcon("D:/imagesCorona/cry.png");
                    resIcon.setIcon(a);
                    resLabel.setText("Vous avez de grande chance à être infecté");
                    resIcon.setVisible(true);
                    resLabel.setVisible(true);
                    conseil.setVisible(true);
                    JOptionPane.showMessageDialog(null, "Vous avez de grande chance à être infecté si vous etiez très \nproche d'un individu infecté qui ne portait pas de masque ou que vous avez\ntoucher un individu ou un objet infecté\nSi c'est le cas, consultez un médecin au plus vite et fait un test");

                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Veuillez d'abord répondre aux question ci-dessous et valider pour les analyser votre cas");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void gelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gelMouseClicked
        if(gel.isSelected()){
            inf.setEnabled(true);
            sup.setEnabled(true);
        }
        else{
            inf.setSelected(false);
            sup.setSelected(false);
            inf.setEnabled(false);
            sup.setEnabled(false);
        }
    }//GEN-LAST:event_gelMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new Arbre().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoronaPrediction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoronaPrediction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoronaPrediction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoronaPrediction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoronaPrediction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel conseil;
    private javax.swing.JTextArea fait;
    private javax.swing.JTextArea fait1;
    private javax.swing.JCheckBox gel;
    private javax.swing.JRadioButton inf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox masque;
    private javax.swing.JRadioButton non;
    private javax.swing.JRadioButton oui;
    private javax.swing.JLabel resIcon;
    private javax.swing.JLabel resLabel;
    private javax.swing.JRadioButton sup;
    private javax.swing.JComboBox<String> touche;
    // End of variables declaration//GEN-END:variables
}
